<?php
echo $this->headlink();
?>
<div style="width:786px; margin: 0 auto;"> 

<?php 
if($this->all==true)
{
	foreach($this->all as $item){?>
    <div style="width:390px; height:130px; float:left; border:#06f thin solid">
    <?php 
    echo $item['tensp']."</br>";
    echo "<a href='".HOST_PROJECT."/public/image/".$item['hinh']."' rel='gallery'  class='pirobox_gall' >
            <img class='img1' src='".HOST_PROJECT."/public/image/".$item['hinh']."'/>
       </a> "."<br>";
	echo $item['gia'];
	 ?>
    </div>
    
    <?php 
    }}
    else
    {
    echo "<h1>khong co du lieu</h1>";
    }
?>



</div>

<div style='clear:both; text-align:center; '>
<?php	
if($this->all==true){
echo  $this->paginationControl($this->all,'Sliding','control.phtml',array("tensp"=>$this->tensp,"idnhom"=>$this->idnhom));}

?>
</div>
