<div style="padding: 8px;">
    <table style="width: 300px;">
        <tbody>
            <tr>
                <td>Username:</td>
                <td><?php echo $this->element->getElement('username'); ?></td>
            </tr>
            <tr>
                <td>Password :</td>
                <td><?php echo $this->element->getElement('password'); ?></td>
            </tr>
			<tr>
                <td>RePassword :</td>
                <td><?php echo $this->element->getElement('passwords'); ?></td>
            </tr>
        </tbody>
    </table>
    <?php echo $this->element->getElement('submit-button'); ?>
</div>
